"""Golden vector conformance: the plugin must reproduce the Budabit client.

``vectors/budabit-policy-vectors.json`` is generated by
``src/app/core/community-policy-vectors.test.ts`` in the Budabit repository
(run with ``POLICY_VECTORS_OUT`` set). Each scenario lists the authority
events (definition, shards, reports, deletes) and a set of candidate events
with the decision the client's own permission code reached. The plugin
replays the authority events and must accept exactly the candidates the
client admits.

Reports are compared through the *effective* state as well: for a person
report the client's ``canPublishCommunityPersonReport`` is the oracle, for an
event report the client accepts it as a moderator event report or a member
content report.
"""

import json
import unittest
from pathlib import Path

from fixtures import config
from policy.budabit import protocol as P
from policy.budabit import rules
from policy.budabit.state import CommunityState, can_read_community

VECTORS = Path(__file__).with_name("vectors") / "budabit-policy-vectors.json"


def load_vectors():
    with VECTORS.open("r", encoding="utf-8") as handle:
        return json.load(handle)


class VectorTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.vectors = load_vectors()
        cls.config = config(BUDABIT_BRANCHES=",".join(cls.vectors["branches"]))

    def replay(self, scenario):
        state = CommunityState(list(self.vectors["branches"]))
        for branch in state.branches.values():
            branch.warm = True
        for event in sorted(scenario["authority"], key=lambda e: (e["created_at"], e["id"])):
            state.apply(event)
        return state

    def test_format(self):
        self.assertEqual(self.vectors["format"], 1)
        self.assertTrue(self.vectors["scenarios"])
        self.assertTrue(self.vectors["definitions"])

    def test_scenarios_match_client(self):
        mismatches = []
        total = 0
        for scenario in self.vectors["scenarios"]:
            state = self.replay(scenario)
            for case in scenario["cases"]:
                total += 1
                outcome = rules.evaluate(case["event"], state, self.config)
                got = "accept" if outcome.accepted else "reject"
                if got != case["expect"]:
                    mismatches.append(
                        f"[{scenario['name']}] {case['name']}: client={case['expect']} "
                        f"plugin={got} ({outcome.reason}: {outcome.decision.msg})"
                    )
        self.assertGreater(total, 100)
        self.assertEqual(mismatches, [], "\n" + "\n".join(mismatches))

    def test_definition_validity_matches_client(self):
        mismatches = []
        for case in self.vectors["definitions"]:
            try:
                P.parse_definition(case["event"])
                valid = True
                reason = ""
            except P.InvalidEvent as error:
                valid = False
                reason = str(error)
            if valid != case["valid"]:
                mismatches.append(f"{case['name']}: client valid={case['valid']} plugin valid={valid} {reason}")
        self.assertEqual(mismatches, [], "\n" + "\n".join(mismatches))

    def test_readers_match_client(self):
        readers = self.vectors["readers"]
        self.assertEqual(readers["format"], 1)
        total = 0
        for scenario in readers["scenarios"]:
            state = self.replay(scenario)
            branch = state.branch(scenario["branch"])
            for case in scenario["cases"]:
                with self.subTest(scenario=scenario["name"], reader=case["name"]):
                    total += 1
                    self.assertEqual(
                        can_read_community(branch, case["pubkey"], ready=scenario["ready"]),
                        case["allowed"],
                    )
        self.assertGreater(total, 100)


if __name__ == "__main__":
    unittest.main()
